DROP TABLE IF EXISTS tag_service;
DROP TABLE IF EXISTS tag_account;
DROP TABLE IF EXISTS account_post;
DROP TABLE IF EXISTS person_account;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS tag;
/**/
DROP TABLE IF EXISTS tag_service;
DROP TABLE IF EXISTS tag_service;
DROP TABLE IF EXISTS tag_service_account;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS person_service_account;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS service;
